77 add an option to make automatic scene switch time for each scene different
Th0rstenf/Rocksniffer-to-Streamer.bot-extension pull request #107
Opened 2023-04-11 22:10 UTC by Th0rstenf

Implemented with your suggested syntax, e.g.

Scene1, Scene2#7, Scene3#1-25000

Scene1 will fall back to globally configured period:
Scene 2 will use 7 seconds instead
Scene 3 will randomize between 1 and 25000

2023-04-11 22:33 UTC, kozaka-tv commented
There is an exception only in SB, in case no '#' is used in songScenes GlobalVar:

![image](https://user-images.githubusercontent.com/4964462/231303322-f8dc18e4-ad03-4f94-ab80-e9462a642e51.png)

2023-04-11 22:48 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                    string[] temp = songScenesRaw[i].Split("#");
Here, SB (mock works) has some issue with the line. What is somehow weird, as actually, as I do not have '#' in songScenes at all, so the if in 412 is always false.

![image](https://user-images.githubusercontent.com/4964462/231303395-e96bf118-cc85-478d-9917-4039f48fc553.png)

2023-04-11 22:48 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                        string[] temp2 = temp[1].Split("-");
Same as above.

2023-04-11 22:48 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                RANGE
I do not know that this is a rule, but can you change pls. to Fixed and Range?

![image](https://user-images.githubusercontent.com/4964462/231304094-c08049d6-4c13-4ae4-acd0-82921f44a9f8.png)

2023-04-11 22:48 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                if (period == SongScene.Period.RANGE)
![image](https://user-images.githubusercontent.com/4964462/231304394-d900c631-b271-4069-9b85-66ec2d83ce88.png)

2023-04-11 22:51 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +        private int defaultSceneSwitchPeriodInSeconds = 5;
You will have here a small merge conflict in case #106 will be merged. I created a defaultSceneSwitchPeriodInSeconds or similar in Constants, and this is then used.

2023-04-11 22:53 UTC, kozaka-tv requested changes
Please also change readme regarding '#' solution!

2023-04-11 23:23 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                    string[] temp = songScenesRaw[i].Split("#");
I fixed this error.

2023-04-12 01:06 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                    if (switchScenes && ItsTimeToSwitchScene() && songScenes.Length > 1)
Maybe 
`switchScenes && songScenes.Length > 1 && ItsTimeToSwitchScene()` 
would be better, as songScenes.Length most likelly is many times just 1. So shortcut, and ItsTimeToSwitchScene must be not run in case only one songScene.

2023-04-12 09:52 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                        songScenes[i].maximumPeriod = int.Parse(temp2[1]);
I actually set now at start one random. I do not know that this was necessary, but for me, seems logical to set there for the first time.

2023-04-12 18:22 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +                RANGE
I do not think it is a rule at all, it is only a complaint of your IDE. Mine doesn't complain about it. It's also not the first enum we have that uses all caps (I just do it without thinking, as it's our coding guideline at work.)

We should collect such convention issues, and create a contribution.md, maybe add definitions files for VS / Jetbrains for autoformatters. Will stop such discussions for good :)

Changing this, and the StreamApp enum to use UpperCamelCase

2023-04-13 19:12 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                RANGE
Not for nothing Jetbrains IDE tells this I think. But I searched: https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces#naming-enumerations

So actually, Fixed and Range are the correct ones. But as usual :) I am Groot! :)

2023-04-13 19:42 UTC, kozaka-tv approved these changes

2023-04-13 19:42 UTC, merged