60 make logging more modular
Th0rstenf/Rocksniffer-to-Streamer.bot-extension pull request #62
Opened 2023-03-30 22:17 UTC by kozaka-tv

I hope, I made the best possible solution regarding logging and such. Here is an log example of one song in case Log level is INFO:

![image](https://user-images.githubusercontent.com/4964462/228976024-28869e4e-9f53-4508-86a3-1fa870ecc582.png)

If it is Debug, then, the start and end of the process is also logged. Not really more.
More data on Verbose level as default log level in SB is Debug.

Mock logging is also enhanced.

2023-04-01 08:34 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +        public string GetCurrentScene()
Why adding Scene again? It's just duplicated information

2023-04-01 08:34 UTC, Th0rstenf commented on SB_SceneSwitcher/CPHMock.cs
> +        CPHInline cph = new CPHInline();
Better stick to obj here, as our object is indeed NOT cph

2023-04-01 08:34 UTC, Th0rstenf commented on SB_SceneSwitcher/CPHMock.cs
> +        Console.WriteLine(MockAppName + "-------------------------------------------------------");
We can leave this here, but isn't it duplicated with the LogInfo calls in Init?

2023-04-01 08:34 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> -            NONE
IMHO we should leave NONE to have a clear definition in case SB is running but the user hasn't started OBS or SLOBS yet. This is not necessarily an eror

2023-04-01 08:34 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +                _ => throw new Exception(MessageNoStreamProgramDefined)
I wouldn't throw an exception here, as we can not distinguish why no program is connected. It might just be the user hasn't started it yet

2023-04-01 08:34 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +}
I like the idea of putting all constants in a class, but why a class, why not a struct?
And maybe we can identify more constants to put in here. It's good to have a single point of definition 👍

2023-04-01 15:03 UTC, Th0rstenf requested changes
Good you please have a look at the comments?

2023-04-04 12:48 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +}
Yeah. I am not so good in C# :) Can be struct for sure!

2023-04-04 12:56 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                _ => throw new Exception(MessageNoStreamProgramDefined)
In the other hand, the user could not know, why it is not working. Therefore the exception. At least, during my stream, if I get an technical problem, I have no time to check code or such...errors in log or error popups are in this case very handy. If the user is just not started some Brodacasting SW, no problem...it is just logs out everything, till some is turned on. It could be also, that the connection is wrongly set, so, our app can not connect. This way, the problem is more visible I think. Still we can not use CPH.LogError() what is not good...I would log out an Error Log with human readable message and trace.

2023-04-04 13:07 UTC, kozaka-tv commented on SB_SceneSwitcher/CPHMock.cs
> +        Console.WriteLine(MockAppName + "-------------------------------------------------------");
Not everything is a dupe, so I will keep it also. It is then very visible, what in the config of the Mock is set. Therefore I used the [MOCK] prefix to see this difference.

[MOCK] ----------- CONFIG ------------------------------------
[MOCK] sniffIP=192.168.178.48
[MOCK] sniffPort=9938
[MOCK] songScenes=ROCKSMITH, ROCKSMITH has, ROCKSMITH gitár, ROCKSMITH gitár nagy, ROCKSMITH fentrol, ROCKSMITH kamerák
[MOCK] menuScene=ROCKSMITH menu
[MOCK] pauseScene=ROCKSMITH pause
[MOCK] sectionDetection=True
[MOCK] behavior=WhiteList
[MOCK] switchScenes=True
[MOCK] sectionActions=True
[MOCK] blackList=START, BREAK, BREAK - BIKINI, POSE, NAGY, PODCAST kicsi, KING OF THE MOSHPIT, GAME OVER, SC Rocksmith menü, SC Overlay, SC Rock full, SC Now Playing, SC Videó effektek, SC Videó effektek - Tuz, SC Emote counter, SC Kamerák, SC Boldog születésnapot
[MOCK] logLevel=INFO
[MOCK] logLevelSB=INFO
[MOCK] -------------------------------------------------------
[ 2023. 04. 04. 15:04:44 INF] RS2SB :: !!! Initialising RockSniffer to SB plugin !!!
[ 2023. 04. 04. 15:04:44 INF] RS2SB :: Sniffer ip configured as 192.168.178.48:9938
[ 2023. 04. 04. 15:04:44 INF] RS2SB :: Menu scene: ROCKSMITH menu
[ 2023. 04. 04. 15:04:44 INF] RS2SB :: Song scenes: ROCKSMITH, ROCKSMITH has, ROCKSMITH gitár, ROCKSMITH gitár nagy, ROCKSMITH fentrol, ROCKSMITH kamerák
[ 2023. 04. 04. 15:04:44 INF] RS2SB :: Song paused scene: ROCKSMITH pause
[ 2023. 04. 04. 15:04:44 INF] RS2SB :: Switching scenes configured to True
[ 2023. 04. 04. 15:04:44 INF] RS2SB :: Section actions are configured to True
[ 2023. 04. 04. 15:04:44 WRN] RS2SB :: behaviorString='WhiteList'
[ 2023. 04. 04. 15:04:44 INF] RS2SB :: Behavior configured as: WhiteList
[ 2023. 04. 04. 15:04:44 INF] RS2SB :: setCurrentScene to 'ROCKSMITH menu'

2023-04-04 13:19 UTC, kozaka-tv commented
The main problem what I see is here with error logging, that SB guys will not allow to send Error level logs. So, if we catch exceptions or do not throw a new exception, then the first option is, that we use LogInfo. But then we convert all errors into information, what is actually not perfect. User could think like "yeah, this is good to know, but who cares!".

For example, if the connection to RockSniffer is not available, that is a problem what the user should fix. If it is temporary (like SB is started, but Sniffer not), who cares if the log is longer? And as in SB the log level is Debug as default, many useless information will be logged out, and an small info line will be maybe not visible regarding the problem. And the user - if ever checks the log file - will just stay there, and asking "why is it just not working?".

So according to my experience and to the possibilities, the best option is, to throw a new or rethrow an known exception with a new, more human readable error message. Like "Can not connect to Sniffer. Please check connection. IP: 1.2.3.4 port: 5678".

This was the way I thought would be good, and thought I throw errors, rather than log out a line about the problem, or even do nothing.

2023-04-04 16:44 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +        public string GetCurrentScene()
The method is of class SceneInteractor. Scene is literally in the name. Call in the program is
 itsSceneInteractor.GetCurrent() so there is no really ambiguity
renaming it to GetActualBroadcastingSoftwareScene is just more explicit but does not add any value at all as there is no other possible context for a scene

2023-04-04 16:45 UTC, Th0rstenf commented on SB_SceneSwitcher/CPHMock.cs
> +        CPHInline cph = new CPHInline();
cphinline is ok, cph is just misleading

2023-04-04 17:47 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> -            NONE
It's still not an error. Just because you don't see an use case doesn't mean there is none.
E.g. implementing more functionality based on acquired data within streamer.bot this could e.g. be used for tracking statistics, having a training log etc.

If you throw an exception, it will immediately stop the action and also won't execute actions that were added by the user afterwards. It will also not gather data even if it is configured to be always on.
So it is better to just handle the case that nothing is connected properly.

2023-04-04 17:50 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +                _ => throw new Exception(MessageNoStreamProgramDefined)
If the user sees that it is not working, it means that the program is started. If it is still not working it means that he didn't set up the connection to (SL)OBS up, which is already mentioned in the readme and in the tutorial video.

sure we can still log it, but throwing an exception is completely unnecessary as there are still potential use cases for the program to run even without a broadcast in mind

2023-04-04 18:14 UTC, Th0rstenf requested changes

2023-04-04 18:14 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +                CPH.LogInfo(Constants.AppName + "Blacklisted scenes: " + string.Join(", ", blackListedScenes));
Why joining the array, it would help much more directly logging the user input e.g.
`
blackListetScenesRaw = CHP.GetGlobalVar<string>("blackList");
blackListedScenes = Regex.Split(blackListedScenesRaw.Trim(), @"\s*[,;]\s*");
`
then you can log directly log the raw input.

2023-04-04 18:14 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +            return stage.Contains("tuner") ? GameStage.InTuner : GameStage.Menu;
I still prefer having a single point of return. At least don't use the ? : operator in the return, as it makes it impossible to set a breakpoint to a certain state in debugging.

2023-04-04 18:14 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +                    throw new Exception(MessageNoStreamProgramDefined);
The user doesn't define the streamer program, it is recognized automatically. For this reason it should rather be MessageNoStreamProgramConnected.
Also for the reasons stated above, an exception is not a good idea here.

2023-04-05 09:25 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +        public string GetCurrentScene()
But then SwitchToScene is also wrong :) Should be SwitchTo only.

So 2 options we got:

1) SceneInteractor with 2 public methods: GetCurrent, SwitchTo
2) or have a different name like: BroadcastingSoftwareController with methods GetCurrentScene and SwitchToScene.

For me, 2nd option is more self explaining.

I think SceneInteractor is a kind of controller or service, so it controls the scenes in OBS or SLOBS. Therefore we got now 2 methods, a getter (GetCurrent) and setter (SwitchToScene). There is no interaction at all.

Which one do you like more?
(This is so offtopic :) )

2023-04-05 12:12 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> -            NONE
I red the code a bit more now, and I think the logic is not optimal if the app is used for different stuffs for the same time and not only for switching scenes.

Let's say, OBS is not started, but Sniffer, RS and SB yes. And you wanna collect/log stats. Will not work, because itsNotRelevant==false, as no Broadcasting app detected. We must separate the Sniffer and OBS logic I think. They should work independently. Then, ok.

And all the different main functions should be configurable in SB (on/off at first place). But this is a different story. I will raise a new issue regarding this and "revert" the exception part. No exception will be thrown, just it is logged out and the app continues.

2023-04-05 12:13 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                _ => throw new Exception(MessageNoStreamProgramDefined)
Will be resolved/reverted as described before.

2023-04-05 12:18 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +        public string GetCurrentScene()
I set it back to GetCurrent() and raise an new issue regarding this.

2023-04-05 12:21 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +            CPH.LogWarn(Constants.AppName + "behaviorString='" + behaviorString + "'");
Was for debugging purposes in CPH added only and forget to delete, sorry!

I deleted it completely!

2023-04-05 12:29 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                CPH.LogInfo(Constants.AppName + "Blacklisted scenes: " + string.Join(", ", blackListedScenes));
It is more important, what the system is detected as list. For example:

raw: "Scene1,Scene2,   Scene3, Scene4    ,, ,Scene5"
is actually just: "Scene1, Scene2, Scene3, Scene4, Scene5"

But, because this happens only once, and actually a good idea to have also the user values in log, I added some Verbose level log, to the raw.

2023-04-05 12:40 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                    throw new Exception(MessageNoStreamProgramDefined);
Good point! I will rename it.

Maybe we should consider also to rename stuffs from BroadcastingSoftware to Stream App as it is in SB.

2023-04-05 12:41 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +                    throw new Exception(MessageNoStreamProgramDefined);
[2023-04-05 14:40:36.811 DBG] RS2SB :: No stream app connection available! Please set and connect either to OBS or SLOBS under 'Stream Apps' in SB!

2023-04-05 13:37 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +            return stage.Contains("tuner") ? GameStage.InTuner : GameStage.Menu;
It is common, if you do not do anything with the calculated value, just use return. Then it is more clear. But if you use the value later in the same method, use single point of return.

However, the calculation of this value could be always extracted into a smaller method, then inside the method again, use return, and then the main method, is just calling this, to get the value, so, single point of return.

Opinion based, but more common is for clean code, to split up into smaller peace of code a method with high complexity and avoid - if it makes sense - the single point of return solution.

I split up to if, but for debugging and testing, normally we do not change the code. For readability, yes! And the ?: solution is not the best to read. Like: 

`
return stage.Equals("las_game") || stage.Equals("sa_game") ? GameStage.InSong : stage.Contains("tuner") ? GameStage.InTuner : GameStage.Menu;
`

I for sure do not understand for the first sight :) But this is good:
`            if (stage.Equals("las_game") || stage.Equals("sa_game"))
                return GameStage.InSong;

            if (stage.Contains("tuner"))
                return GameStage.InTuner;

            return GameStage.Menu;
`

2023-04-05 13:45 UTC, kozaka-tv commented
I hopefully changed everything as we discussed here and pushed now. Also develop is now merged (had some merge conflicts, so I hope it is good). Can you please check?

2023-04-05 16:39 UTC, Th0rstenf approved these changes

2023-04-05 16:39 UTC, merged