72 add an option to disable the automatic scene switching
Th0rstenf/Rocksniffer-to-Streamer.bot-extension pull request #93
Opened 2023-04-08 23:52 UTC by kozaka-tv

2023-04-09 09:13 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +        private bool IsSongScene(string scene)
If you change it to private again, you implicitly say we won't unit test it. That's certainly OK for this method, just something to keep in mind.

2023-04-09 09:21 UTC, Th0rstenf requested changes

2023-04-09 09:21 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +
Wrapping all variable access is not a bad idea, but it should be in a separate subclass, so it can be passed to other subclasses.
If we introduce an abstraction layer, it needs to available everywhere. A singleton access or static methods would totally be acceptable here.

That being said, this refactoring has nothing to do with the original intent of this issue. Please stay in scope in the future.

2023-04-09 09:21 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +                    itsSceneInterActor.SwitchToScene(songScenes[currentSongSceneIndex], switchScenes);
switchScenes is something that the SceneInteractor should be aware of. It could be passed to its during initialization.

2023-04-09 09:21 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +        snifferPort = GetSnifferPort();
Again out of scope, but thanks for fixing it. Stumbled over it recently and was like 😵‍💫

2023-04-09 09:30 UTC, Th0rstenf commented on SB_SceneSwitcher/Program.cs
> +
Created new issue

2023-04-09 09:31 UTC, merged

2023-04-13 20:29 UTC, kozaka-tv commented on SB_SceneSwitcher/Program.cs
> +        private bool IsSongScene(string scene)
Well, never test a private method! :) If, to test the main method is too complex, too many test Data, etc., then we have to extract some codes into other classes to have them separated from the main method, and then test them there.

If this is not possible here with SB and so, then, in case we start to write test, the could be changed back to public. But I would awoid this.